API_ID = "YOUR_TELEGRAM_API_ID"
API_HASH = "YOUR_TELEGRAM_API_HASH"
BOT_TOKEN = "YOUR_TEJAS_BOT_TOKEN"
OPENAI_API_KEY = "YOUR_OPENAI_API_KEY"
GOOGLE_API_KEY = "YOUR_GOOGLE_CLOUD_VISION_API_KEY"
LOG_CHANNEL_ID = -1001234567890  # Apne private log group ka ID daalo
BOT_NAME = "Tejas"
